### ISSUE TITLE
problems setting up `typesafe-i18n`?

### ISSUE THREAD

**Issue by ivanhofer** [artesgo/reminders#1]
Hi,
I just came across your repo and saw you are using `typesafe-i18n` in a way that doesn't offer full typesafety. Is this intended?
Normally you would use the [`generator`](https://github.com/ivanhofer/typesafe-i18n#typesafety) to create typesafe wrappers for your translations. Let me know if I can help :)

**Comment by artesgo** [comment]
hey Ivan, thanks for the advice.
I'm still working on the i18n feature for this ext, I did notice it wasn't getting the types properly so I'll look into it!

**Comment by artesgo** [comment]
very cool, didn't read the docs too thoroughly the first time so missed the crucial details!
